#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:/com/example/mapper/xml/*.xml #注意 classpath* 后边的 * 星号表示扫描引入的jar包下边的classpath里边的配置文件
  #  mapper-locations: classpath*:mapper/**/*.xml  #注意 classpath* 后边的 * 星号表示扫描引入的jar包下边的classpath里边的配置文件
  global-config:
    banner: false # 关闭MP3.0自带的banner
    db-config:
      id-type: ASSIGN_ID #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      table-underline: true # 默认数据库表下划线命名
  configuration:
    map-underscore-to-camel-case: false #不使用驼峰原模原样对应
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true