server:
  port: 9999

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      filter: stat,wall,log4j  #druid监控
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
#redis配置
  redis:
    host: 10.10.111.136
    port: 6379
    password:
    database: 0
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: 300ms
#        max-idle: 16
#        min-idle: 8


  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    prefix: classpath:/templates/
    suffix: .html  #后缀名
    encoding: utf-8  #编码
    cache: false  #是否使用缓存

#    mode: HTML  #严格的HTML语法模式


#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:/com/example/mapper/xml/*.xml #注意 classpath* 后边的 * 星号表示扫描引入的jar包下边的classpath里边的配置文件
#  mapper-locations: classpath*:mapper/**/*.xml  #注意 classpath* 后边的 * 星号表示扫描引入的jar包下边的classpath里边的配置文件
  global-config:
    banner: false # 关闭MP3.0自带的banner
    db-config:
      id-type: ASSIGN_ID #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      table-underline: true # 默认数据库表下划线命名
  configuration:
    map-underscore-to-camel-case: false #不使用驼峰原模原样对应
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true


#showSql
logging:
  level: trace
  level.com.example: trace
  level.com.example.mapper: debug
  level.com.example.demo: info
  path: ./log/
  file: demo.log





